[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Joseph Bradshaw <joseph.bradshaw@statkraft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.69.4"
ferris-says = "0.3.1"
ggez = "0.9.3"
