[package]
name = "rong"
version = "0.1.1"
authors = ["Joseph Bradshaw <joseph.bradshaw@statkraft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
mint = "0.5.9"
